secret_id = "你的云API密钥ID"
secret_key = "你的云API密钥KEY"
service = "cwp"
host="%s.tencentcloudapi.com" % service
#host = "cwp.tencentcloudapi.com"
endpoint = "https://%s" % host
region = "ap-guangzhou"
action = "DescribeAssetUserList"
version = "2018-02-28"